### PR TITLE
Fix url regexp to remove file extension for request with params

### PR DESCRIPTION
**Pull request by RoobinGood**

### CODE REVIEW

**Comment by okv** [comment]
Fair enough, how about also change `+` to `*` at `(\?.+$|$)`? to provide replacing when only `?`, without query string params.
Descriptive commit message (something like current pull request title) is required.

**Comment by RoobinGood** [comment]
@okv, commit message and regexp fixed.

**Comment by okv** [comment]
:+1:

**Comment by okv** [comment]
version 0.1.5 with that changes published to npm

**Pull request merged**
